/**
 * @File: mapping_code_subcat.js
 * @Author: Jagdish Prasad ACHARA
 * @Date: October 2015.
 * @CopyRight: Privatics team, Inria 2015
 *
 */

var mapping_code_subcat = {
0: "adult/general",
1: "adult/pornography",
2: "agriculture/general",
3: "animals/general",
4: "animals/desert and arctic animals",
5: "animals/farm animals",
6: "animals/forest animals",
7: "animals/insects",
8: "animals/jungle animals",
9: "animals/savannah animals",
10: "animals/sea animals",
11: "animals/swamp animals",
12: "architecture/general",
13: "arts & entertainment/general",
14: "arts & entertainment/animation",
15: "arts & entertainment/celebrities",
16: "arts & entertainment/comics",
17: "arts & entertainment/design",
18: "arts & entertainment/fine art",
19: "arts & entertainment/humor",
20: "arts & entertainment/literature",
21: "arts & entertainment/movies",
22: "arts & entertainment/music",
23: "arts & entertainment/opera",
24: "arts & entertainment/poetry",
25: "arts & entertainment/radio",
26: "arts & entertainment/television",
27: "arts & entertainment/theatre",
28: "arts & entertainment/video games",
29: "automotive/general",
30: "automotive/auto parts",
31: "automotive/car brands",
32: "automotive/car culture",
33: "automotive/convertibles",
34: "automotive/coupe cars",
35: "automotive/hatchbacks",
36: "automotive/luxury cars",
37: "automotive/minivans",
38: "automotive/motorcycles",
39: "automotive/off-road vehicles",
40: "automotive/performance vehicles",
41: "automotive/pickup trucks",
42: "automotive/sedan cars",
43: "automotive/wagons",
44: "business/general",
45: "business/advertising",
46: "business/biomedical",
47: "business/biotech",
48: "business/commerce",
49: "business/construction",
50: "business/ecommerce",
51: "business/energy",
52: "business/forestry",
53: "business/green solutions",
54: "business/human resources",
55: "business/logistics",
56: "business/manufacturing",
57: "business/marketing",
58: "business/metals",
59: "business/mining",
60: "business/non profit",
61: "business/publishing",
62: "business/shipping",
63: "careers/general",
64: "careers/career advice",
65: "careers/career planning",
66: "careers/job fairs",
67: "careers/job search",
68: "economics/general",
69: "education/general",
70: "education/academia",
71: "education/english as a 2nd language",
72: "education/graduate school",
73: "education/homeschooling",
74: "education/languages",
75: "education/special education",
76: "education/university",
77: "family & parenting/general",
78: "family & parenting/childrens",
79: "family & parenting/parenting",
80: "family & parenting/parenting children",
81: "family & parenting/parenting teenagers",
82: "family & parenting/pregnancy",
83: "fashion/general",
84: "fashion/beauty",
85: "fashion/body art",
86: "fashion/clothing",
87: "fashion/fashion accessories",
88: "fashion/jewelry",
89: "folklore/general",
90: "folklore/astrology",
91: "folklore/magic & illusions",
92: "folklore/paranormal phenomena",
93: "food & drink/general",
94: "food & drink/american cuisine",
95: "food & drink/baking",
96: "food & drink/barbecues & grilling",
97: "food & drink/beer",
98: "food & drink/cheese",
99: "food & drink/chinese cuisine",
100: "food & drink/cider",
101: "food & drink/cocktails",
102: "food & drink/coffee",
103: "food & drink/cooking",
104: "food & drink/dining out",
105: "food & drink/fruit",
106: "food & drink/healthy cooking",
107: "food & drink/italian cuisine",
108: "food & drink/japanese cuisine",
109: "food & drink/mexican cuisine",
110: "food & drink/pasta",
111: "food & drink/tea",
112: "food & drink/vegan",
113: "food & drink/vegetarian",
114: "food & drink/wine",
115: "health & fitness/general",
116: "health & fitness/aids hiv",
117: "health & fitness/alternative medicine",
118: "health & fitness/anatomy",
119: "health & fitness/asthma",
120: "health & fitness/autism",
121: "health & fitness/bowel incontinence",
122: "health & fitness/brain tumor",
123: "health & fitness/cancer",
124: "health & fitness/cardiac arrest",
125: "health & fitness/chronic pain",
126: "health & fitness/cold & flu",
127: "health & fitness/deafness",
128: "health & fitness/dental care",
129: "health & fitness/dermatology",
130: "health & fitness/diabetes",
131: "health & fitness/dieting",
132: "health & fitness/epilepsy",
133: "health & fitness/exercise",
134: "health & fitness/eye care",
135: "health & fitness/first aid",
136: "health & fitness/heart disease",
137: "health & fitness/medicine",
138: "health & fitness/men's health",
139: "health & fitness/mental depression",
140: "health & fitness/nutrition",
141: "health & fitness/orthopedics",
142: "health & fitness/pediatrics",
143: "health & fitness/physical therapy",
144: "health & fitness/psychology & psychiatry",
145: "health & fitness/senior health",
146: "health & fitness/sexuality",
147: "health & fitness/sleeping disorders",
148: "health & fitness/smoking cessation",
149: "health & fitness/stress",
150: "health & fitness/substance abuse",
151: "health & fitness/thyroid disease",
152: "health & fitness/vitamins",
153: "health & fitness/weight loss",
154: "health & fitness/women's health",
155: "history/general",
156: "history/archaeology",
157: "hobbies & interests/general",
158: "hobbies & interests/antiques",
159: "hobbies & interests/arts & crafts",
160: "hobbies & interests/birdwatching",
161: "hobbies & interests/board games",
162: "hobbies & interests/coins",
163: "hobbies & interests/dance",
164: "hobbies & interests/drawing",
165: "hobbies & interests/drugs",
166: "hobbies & interests/gambling",
167: "hobbies & interests/genealogy",
168: "hobbies & interests/horse racing",
169: "hobbies & interests/metalworking",
170: "hobbies & interests/needlework",
171: "hobbies & interests/painting",
172: "hobbies & interests/photography",
173: "hobbies & interests/pottery",
174: "hobbies & interests/sci-fi",
175: "hobbies & interests/scouting",
176: "hobbies & interests/smoking",
177: "hobbies & interests/stamps",
178: "hobbies & interests/woodworking",
179: "hobbies & interests/writing",
180: "home/general",
181: "home/gardening",
182: "home/home appliances",
183: "home/home repair",
184: "home/interior design",
185: "home/landscaping",
186: "law/general",
187: "law/crime",
188: "law/immigration",
189: "military/general",
190: "military/terrorism",
191: "news/general",
192: "news/international news",
193: "news/journalism",
194: "news/local news",
195: "news/national news",
196: "news/weather",
197: "personal finance/general",
198: "personal finance/banking",
199: "personal finance/credit, debt & loans",
200: "personal finance/cryptocurrencies",
201: "personal finance/financial news",
202: "personal finance/financial planning",
203: "personal finance/insurance",
204: "personal finance/investing",
205: "personal finance/retirement planning",
206: "personal finance/stocks",
207: "personal finance/tax planning",
208: "pets/general",
209: "pets/aquariums",
210: "pets/birds",
211: "pets/cats",
212: "pets/dogs",
213: "pets/reptiles",
214: "philosophy/general",
215: "politics/general",
216: "politics/government",
217: "real estate/general",
218: "real estate/buying & selling homes",
219: "real estate/mortgages",
220: "religion/general",
221: "religion/buddhism",
222: "religion/christianity",
223: "religion/hinduism",
224: "religion/islam",
225: "religion/judaism",
226: "religion/shinto",
227: "religion/wicca",
228: "science/general",
229: "science/astronomy",
230: "science/biology",
231: "science/botany",
232: "science/chemistry",
233: "science/geography",
234: "science/geology",
235: "science/mathematics",
236: "science/mechanics",
237: "science/palaeontology",
238: "science/physics",
239: "science/virology",
240: "science/zoology",
241: "society/general",
242: "society/anthropology",
243: "society/dating",
244: "society/gay life",
245: "society/marriage",
246: "society/social networking",
247: "society/sociology",
248: "sports/general",
249: "sports/american football",
250: "sports/archery",
251: "sports/athletics",
252: "sports/baseball",
253: "sports/basketball",
254: "sports/bodybuilding",
255: "sports/bowling",
256: "sports/boxing",
257: "sports/cheerleading",
258: "sports/climbing",
259: "sports/cricket",
260: "sports/cycling",
261: "sports/darts",
262: "sports/diving",
263: "sports/fencing",
264: "sports/fishing",
265: "sports/golf",
266: "sports/gymnastics",
267: "sports/hockey",
268: "sports/horse riding",
269: "sports/hunting",
270: "sports/jogging",
271: "sports/kayaking",
272: "sports/lacrosse",
273: "sports/martial arts",
274: "sports/olympics",
275: "sports/racing",
276: "sports/rowing",
277: "sports/rugby",
278: "sports/running",
279: "sports/sailing",
280: "sports/shooting",
281: "sports/skateboarding",
282: "sports/skating",
283: "sports/skiing",
284: "sports/snowboarding",
285: "sports/soccer",
286: "sports/surfing",
287: "sports/swimming",
288: "sports/tennis",
289: "sports/volleyball",
290: "sports/walking",
291: "sports/wrestling",
292: "sports/yoga",
293: "technology & computing/general",
294: "technology & computing/apple",
295: "technology & computing/audio",
296: "technology & computing/business software",
297: "technology & computing/cameras & video",
298: "technology & computing/cell phones",
299: "technology & computing/computer architecture",
300: "technology & computing/computer graphics",
301: "technology & computing/computer hardware",
302: "technology & computing/computer networking",
303: "technology & computing/computer peripherals",
304: "technology & computing/computer programming",
305: "technology & computing/computer science",
306: "technology & computing/computer security",
307: "technology & computing/computer software",
308: "technology & computing/databases",
309: "technology & computing/desktop publishing",
310: "technology & computing/email",
311: "technology & computing/freeware",
312: "technology & computing/home theatre systems",
313: "technology & computing/internet culture",
314: "technology & computing/internet technology",
315: "technology & computing/mobile apps",
316: "technology & computing/software",
317: "technology & computing/unix",
318: "technology & computing/web design",
319: "technology & computing/web search",
320: "technology & computing/windows",
321: "travel/general",
322: "travel/adventure",
323: "travel/air travel",
324: "travel/budget travel",
325: "travel/cruise vacations",
326: "travel/hotels",
327: "travel/national parks",
328: "travel/theme parks",
329: "travel/trains"
};
