/**
 * @File: mapping_subcat_code.js
 * @Author: Jagdish Prasad ACHARA
 * @Date: October 2015.
 * @CopyRight: Privatics team, Inria 2015
 *
 */


var mapping_subcat_code = {
"adult/general": 0,
"adult/pornography": 1,
"agriculture/general": 2,
"animals/general": 3,
"animals/desert and arctic animals": 4,
"animals/farm animals": 5,
"animals/forest animals": 6,
"animals/insects": 7,
"animals/jungle animals": 8,
"animals/savannah animals": 9,
"animals/sea animals": 10,
"animals/swamp animals": 11,
"architecture/general": 12,
"arts & entertainment/general": 13,
"arts & entertainment/animation": 14,
"arts & entertainment/celebrities": 15,
"arts & entertainment/comics": 16,
"arts & entertainment/design": 17,
"arts & entertainment/fine art": 18,
"arts & entertainment/humor": 19,
"arts & entertainment/literature": 20,
"arts & entertainment/movies": 21,
"arts & entertainment/music": 22,
"arts & entertainment/opera": 23,
"arts & entertainment/poetry": 24,
"arts & entertainment/radio": 25,
"arts & entertainment/television": 26,
"arts & entertainment/theatre": 27,
"arts & entertainment/video games": 28,
"automotive/general": 29,
"automotive/auto parts": 30,
"automotive/car brands": 31,
"automotive/car culture": 32,
"automotive/convertibles": 33,
"automotive/coupe cars": 34,
"automotive/hatchbacks": 35,
"automotive/luxury cars": 36,
"automotive/minivans": 37,
"automotive/motorcycles": 38,
"automotive/off-road vehicles": 39,
"automotive/performance vehicles": 40,
"automotive/pickup trucks": 41,
"automotive/sedan cars": 42,
"automotive/wagons": 43,
"business/general": 44,
"business/advertising": 45,
"business/biomedical": 46,
"business/biotech": 47,
"business/commerce": 48,
"business/construction": 49,
"business/ecommerce": 50,
"business/energy": 51,
"business/forestry": 52,
"business/green solutions": 53,
"business/human resources": 54,
"business/logistics": 55,
"business/manufacturing": 56,
"business/marketing": 57,
"business/metals": 58,
"business/mining": 59,
"business/non profit": 60,
"business/publishing": 61,
"business/shipping": 62,
"careers/general": 63,
"careers/career advice": 64,
"careers/career planning": 65,
"careers/job fairs": 66,
"careers/job search": 67,
"economics/general": 68,
"education/general": 69,
"education/academia": 70,
"education/english as a 2nd language": 71,
"education/graduate school": 72,
"education/homeschooling": 73,
"education/languages": 74,
"education/special education": 75,
"education/university": 76,
"family & parenting/general": 77,
"family & parenting/childrens": 78,
"family & parenting/parenting": 79,
"family & parenting/parenting children": 80,
"family & parenting/parenting teenagers": 81,
"family & parenting/pregnancy": 82,
"fashion/general": 83,
"fashion/beauty": 84,
"fashion/body art": 85,
"fashion/clothing": 86,
"fashion/fashion accessories": 87,
"fashion/jewelry": 88,
"folklore/general": 89,
"folklore/astrology": 90,
"folklore/magic & illusions": 91,
"folklore/paranormal phenomena": 92,
"food & drink/general": 93,
"food & drink/american cuisine": 94,
"food & drink/baking": 95,
"food & drink/barbecues & grilling": 96,
"food & drink/beer": 97,
"food & drink/cheese": 98,
"food & drink/chinese cuisine": 99,
"food & drink/cider": 100,
"food & drink/cocktails": 101,
"food & drink/coffee": 102,
"food & drink/cooking": 103,
"food & drink/dining out": 104,
"food & drink/fruit": 105,
"food & drink/healthy cooking": 106,
"food & drink/italian cuisine": 107,
"food & drink/japanese cuisine": 108,
"food & drink/mexican cuisine": 109,
"food & drink/pasta": 110,
"food & drink/tea": 111,
"food & drink/vegan": 112,
"food & drink/vegetarian": 113,
"food & drink/wine": 114,
"health & fitness/general": 115,
"health & fitness/aids hiv": 116,
"health & fitness/alternative medicine": 117,
"health & fitness/anatomy": 118,
"health & fitness/asthma": 119,
"health & fitness/autism": 120,
"health & fitness/bowel incontinence": 121,
"health & fitness/brain tumor": 122,
"health & fitness/cancer": 123,
"health & fitness/cardiac arrest": 124,
"health & fitness/chronic pain": 125,
"health & fitness/cold & flu": 126,
"health & fitness/deafness": 127,
"health & fitness/dental care": 128,
"health & fitness/dermatology": 129,
"health & fitness/diabetes": 130,
"health & fitness/dieting": 131,
"health & fitness/epilepsy": 132,
"health & fitness/exercise": 133,
"health & fitness/eye care": 134,
"health & fitness/first aid": 135,
"health & fitness/heart disease": 136,
"health & fitness/medicine": 137,
"health & fitness/men's health": 138,
"health & fitness/mental depression": 139,
"health & fitness/nutrition": 140,
"health & fitness/orthopedics": 141,
"health & fitness/pediatrics": 142,
"health & fitness/physical therapy": 143,
"health & fitness/psychology & psychiatry": 144,
"health & fitness/senior health": 145,
"health & fitness/sexuality": 146,
"health & fitness/sleeping disorders": 147,
"health & fitness/smoking cessation": 148,
"health & fitness/stress": 149,
"health & fitness/substance abuse": 150,
"health & fitness/thyroid disease": 151,
"health & fitness/vitamins": 152,
"health & fitness/weight loss": 153,
"health & fitness/women's health": 154,
"history/general": 155,
"history/archaeology": 156,
"hobbies & interests/general": 157,
"hobbies & interests/antiques": 158,
"hobbies & interests/arts & crafts": 159,
"hobbies & interests/birdwatching": 160,
"hobbies & interests/board games": 161,
"hobbies & interests/coins": 162,
"hobbies & interests/dance": 163,
"hobbies & interests/drawing": 164,
"hobbies & interests/drugs": 165,
"hobbies & interests/gambling": 166,
"hobbies & interests/genealogy": 167,
"hobbies & interests/horse racing": 168,
"hobbies & interests/metalworking": 169,
"hobbies & interests/needlework": 170,
"hobbies & interests/painting": 171,
"hobbies & interests/photography": 172,
"hobbies & interests/pottery": 173,
"hobbies & interests/sci-fi": 174,
"hobbies & interests/scouting": 175,
"hobbies & interests/smoking": 176,
"hobbies & interests/stamps": 177,
"hobbies & interests/woodworking": 178,
"hobbies & interests/writing": 179,
"home/general": 180,
"home/gardening": 181,
"home/home appliances": 182,
"home/home repair": 183,
"home/interior design": 184,
"home/landscaping": 185,
"law/general": 186,
"law/crime": 187,
"law/immigration": 188,
"military/general": 189,
"military/terrorism": 190,
"news/general": 191,
"news/international news": 192,
"news/journalism": 193,
"news/local news": 194,
"news/national news": 195,
"news/weather": 196,
"personal finance/general": 197,
"personal finance/banking": 198,
"personal finance/credit, debt & loans": 199,
"personal finance/cryptocurrencies": 200,
"personal finance/financial news": 201,
"personal finance/financial planning": 202,
"personal finance/insurance": 203,
"personal finance/investing": 204,
"personal finance/retirement planning": 205,
"personal finance/stocks": 206,
"personal finance/tax planning": 207,
"pets/general": 208,
"pets/aquariums": 209,
"pets/birds": 210,
"pets/cats": 211,
"pets/dogs": 212,
"pets/reptiles": 213,
"philosophy/general": 214,
"politics/general": 215,
"politics/government": 216,
"real estate/general": 217,
"real estate/buying & selling homes": 218,
"real estate/mortgages": 219,
"religion/general": 220,
"religion/buddhism": 221,
"religion/christianity": 222,
"religion/hinduism": 223,
"religion/islam": 224,
"religion/judaism": 225,
"religion/shinto": 226,
"religion/wicca": 227,
"science/general": 228,
"science/astronomy": 229,
"science/biology": 230,
"science/botany": 231,
"science/chemistry": 232,
"science/geography": 233,
"science/geology": 234,
"science/mathematics": 235,
"science/mechanics": 236,
"science/palaeontology": 237,
"science/physics": 238,
"science/virology": 239,
"science/zoology": 240,
"society/general": 241,
"society/anthropology": 242,
"society/dating": 243,
"society/gay life": 244,
"society/marriage": 245,
"society/social networking": 246,
"society/sociology": 247,
"sports/general": 248,
"sports/american football": 249,
"sports/archery": 250,
"sports/athletics": 251,
"sports/baseball": 252,
"sports/basketball": 253,
"sports/bodybuilding": 254,
"sports/bowling": 255,
"sports/boxing": 256,
"sports/cheerleading": 257,
"sports/climbing": 258,
"sports/cricket": 259,
"sports/cycling": 260,
"sports/darts": 261,
"sports/diving": 262,
"sports/fencing": 263,
"sports/fishing": 264,
"sports/golf": 265,
"sports/gymnastics": 266,
"sports/hockey": 267,
"sports/horse riding": 268,
"sports/hunting": 269,
"sports/jogging": 270,
"sports/kayaking": 271,
"sports/lacrosse": 272,
"sports/martial arts": 273,
"sports/olympics": 274,
"sports/racing": 275,
"sports/rowing": 276,
"sports/rugby": 277,
"sports/running": 278,
"sports/sailing": 279,
"sports/shooting": 280,
"sports/skateboarding": 281,
"sports/skating": 282,
"sports/skiing": 283,
"sports/snowboarding": 284,
"sports/soccer": 285,
"sports/surfing": 286,
"sports/swimming": 287,
"sports/tennis": 288,
"sports/volleyball": 289,
"sports/walking": 290,
"sports/wrestling": 291,
"sports/yoga": 292,
"technology & computing/general": 293,
"technology & computing/apple": 294,
"technology & computing/audio": 295,
"technology & computing/business software": 296,
"technology & computing/cameras & video": 297,
"technology & computing/cell phones": 298,
"technology & computing/computer architecture": 299,
"technology & computing/computer graphics": 300,
"technology & computing/computer hardware": 301,
"technology & computing/computer networking": 302,
"technology & computing/computer peripherals": 303,
"technology & computing/computer programming": 304,
"technology & computing/computer science": 305,
"technology & computing/computer security": 306,
"technology & computing/computer software": 307,
"technology & computing/databases": 308,
"technology & computing/desktop publishing": 309,
"technology & computing/email": 310,
"technology & computing/freeware": 311,
"technology & computing/home theatre systems": 312,
"technology & computing/internet culture": 313,
"technology & computing/internet technology": 314,
"technology & computing/mobile apps": 315,
"technology & computing/software": 316,
"technology & computing/unix": 317,
"technology & computing/web design": 318,
"technology & computing/web search": 319,
"technology & computing/windows": 320,
"travel/general": 321,
"travel/adventure": 322,
"travel/air travel": 323,
"travel/budget travel": 324,
"travel/cruise vacations": 325,
"travel/hotels": 326,
"travel/national parks": 327,
"travel/theme parks": 328,
"travel/trains": 329
};
